In [201]:
import pandas as pd
import json

In [202]:
results = pd.DataFrame(json.loads(open("../nl_testgeneration_framework/test_outputs/ae7d024d800f4dfdac8153683f958c95/all_results.json").read()))

In [203]:
stat_mapping = json.loads(open("../nl_testgeneration_framework/stat_mapping/MBB/Player.json").read())

In [204]:
stat_mapping = {x["stat"].lower() : x for x in stat_mapping}

In [205]:
import re

In [206]:
stat_pattern = re.compile("(s_[a-z0-9_]+)(\s|$)")

In [207]:
stat_pattern.findall("s_fieid_goal_made_longest and s_rushing_yards_net")

[('s_fieid_goal_made_longest', ' '), ('s_rushing_yards_net', '')]

In [208]:
new_recs = [] 
for i,x in results.iterrows():
   
    
    #ground_stat = x["ground_truth_aql"]["conditions"].lower().replace("is not null", "").strip()
    ground_conditions = x["ground_truth_aql"]["conditions"].lower().replace("<=","<").replace(">=",">")
    ground_stats = [t[0] for t in stat_pattern.findall(ground_conditions)]
    
    x["ground_stats"] = ground_stats
    
    x["pred_conditions"] =  x["predicted_aql"]["conditions"].lower()

    
    pred_stats =  stat_pattern.findall(x["predicted_aql"]["conditions"].lower())
    x["pred_stats"] = [t[0] for t in pred_stats]
    
    x["ground_qtype"] =  x["ground_truth_aql"]["query_type"].lower()
    x["pred_qtype"] =  x["predicted_aql"]["query_type"].lower()
    
    if x["ground_stats"] != x["pred_stats"]:
        x["stat_matched"] = False
    else:
        x["stat_matched"] = True
    
    if x["ground_qtype"] != x["pred_qtype"]:
        x["qtype_matched"] = False
    else:
        x["qtype_matched"] = True
        
    x["categories"] = [stat_mapping[y]["category"] for y in ground_stats]
    # x["sub_categories"] = [stat_mapping[y]["sub_category"] for y in ground_stats]
    
    new_recs.append(x)

In [209]:
new_recs = pd.DataFrame(new_recs)

In [210]:
export = new_recs[["query",  "categories", "ground_stats", "pred_conditions", "pred_stats", "ground_qtype", "pred_qtype", "stat_matched", "qtype_matched"]]

In [211]:
export[export["stat_matched"] == False]

Empty DataFrame
Columns: [query, categories, ground_stats, pred_conditions, pred_stats, ground_qtype, pred_qtype, stat_matched, qtype_matched]
Index: []

In [212]:
true_percentage = len(export[export["stat_matched"] == True]) / len(export)
print(true_percentage)

1.0

In [213]:
export.to_csv("../nl_testgeneration_framework/reports/Player_Min_Max_Template_13.csv")

In [125]:
results = """[{"metadata":{"ID":1740,"DATE":"2018-11-17","POS":"LB","OPP":"Mississippi St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"GREENLAW, DRE","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1816,"DATE":"2019-11-02","POS":"LB","OPP":"Mississippi St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"HENRY, HAYDEN","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":600,"DATE":"2021-09-04","POS":"DL","OPP":"Rice","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"WILLIAMS, TRE","RES":"1"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":476,"DATE":"2021-09-04","POS":"DL","OPP":"Rice","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"CARTER, TAUREAN","RES":"1"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1699,"DATE":"2018-09-15","POS":"LB","OPP":"North Texas","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"HARRIS, DE'JON","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":35,"DATE":"2023-10-14","POS":"LB","OPP":"Alabama","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"GRIER, ANTONIO","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1697,"DATE":"2018-09-01","POS":"LB","OPP":"Eastern Ill.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"HARRIS, DE'JON","RES":"1"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1636,"DATE":"2017-11-24","POS":"DB","OPP":"Missouri","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"LIDDELL, JOSH","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":276,"DATE":"2020-10-10","POS":"LB","OPP":"Auburn","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"MORGAN, GRANT","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":587,"DATE":"2021-09-04","POS":"DB","OPP":"Rice","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"CATALON, JALEN","RES":"1"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":588,"DATE":"2021-09-11","POS":"DB","OPP":"Texas","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"CATALON, JALEN","RES":"1"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1593,"DATE":"2017-11-24","POS":"DB","OPP":"Missouri","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"RICHARDSON II, KEVIN","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":350,"DATE":"2014-09-27","POS":"LB","OPP":"Texas A&M","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"SPAIGHT, MARTRELL","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1712,"DATE":"2018-10-20","POS":"DL","OPP":"Tulsa","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"AGIM, MCTELVIN","RES":"1"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":270,"DATE":"2019-10-19","POS":"LB","OPP":"Auburn","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"HARRIS, DE'JON","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":134,"DATE":"2020-12-12","POS":"DB","OPP":"Alabama","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"FOUCHA, JOE","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1584,"DATE":"2017-11-18","POS":"LB","OPP":"Mississippi St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"GREENLAW, DRE","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1572,"DATE":"2017-10-28","POS":"DL","OPP":"Ole Miss","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"SMITH, T.J.","RES":"1"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":576,"DATE":"2021-10-09","POS":"S","OPP":"Ole Miss","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"BROOKS JR., GREG","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":975,"DATE":"2024-09-14","POS":"LB","OPP":"UAB","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"DIX JR., STEPHEN","RES":"1"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1568,"DATE":"2017-11-18","POS":"DL","OPP":"Mississippi St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"AGIM, MCTELVIN","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":263,"DATE":"2019-10-19","POS":"LB","OPP":"Auburn","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"POOL, BUMPER","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":889,"DATE":"2023-09-09","POS":"DB","OPP":"Kent St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"JOHNSON, JAYDEN","RES":"1"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1562,"DATE":"2017-11-18","POS":"LB","OPP":"Mississippi St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"HARRIS, DE'JON","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1022,"DATE":"2024-12-27","POS":"LB","OPP":"Texas Tech","CLASS":"JUNIOR","TEAM":"Arkansas","PLAYER":"SOREY, XAVIAN","RES":"1"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":671,"DATE":"2022-11-05","POS":"DB","OPP":"Liberty","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"BLAIR, SIMEON","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1076,"DATE":"2024-11-02","POS":"DB","OPP":"Ole Miss","CLASS":"SOPHOMORE","TEAM":"Arkansas","PLAYER":"METCALF, TJ","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":1713,"DATE":"2018-11-10","POS":"DL","OPP":"LSU","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"AGIM, MCTELVIN","RES":"0"},"stats":{"DTACKA":"5"}},{"metadata":{"ID":881,"DATE":"2023-09-16","POS":"LB","OPP":"BYU","CLASS":"SOPHOMORE","TEAM":"Arkansas","PLAYER":"PAUL JR., CHRIS","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1497,"DATE":"2016-11-05","POS":"DL","OPP":"Florida","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"LEDBETTER, JEREMIAH","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1494,"DATE":"2016-09-03","POS":"DL","OPP":"Louisiana Tech","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"LEDBETTER, JEREMIAH","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":532,"DATE":"2021-10-02","POS":"LB","OPP":"Georgia","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"POOL, BUMPER","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1496,"DATE":"2016-10-15","POS":"DL","OPP":"Ole Miss","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"LEDBETTER, JEREMIAH","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1506,"DATE":"2016-12-29","POS":"DL","OPP":"Virginia Tech","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"JOHNSON, TAIWAN","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1477,"DATE":"2016-11-19","POS":"LB","OPP":"Mississippi St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"ELLIS, BROOKS","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":521,"DATE":"2021-11-06","POS":"LB","OPP":"Mississippi St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"HENRY, HAYDEN","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":517,"DATE":"2021-09-18","POS":"LB","OPP":"Ga. Southern","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"HENRY, HAYDEN","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":15,"DATE":"2021-11-20","POS":"DB","OPP":"Alabama","CLASS":"JUNIOR","TEAM":"Arkansas","PLAYER":"SLUSHER, MYLES","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":120,"DATE":"2019-10-26","POS":"DB","OPP":"Alabama","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"FOUCHA, JOE","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":879,"DATE":"2023-09-02","POS":"LB","OPP":"Western Caro.","CLASS":"SOPHOMORE","TEAM":"Arkansas","PLAYER":"PAUL JR., CHRIS","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1483,"DATE":"2016-10-15","POS":"DL","OPP":"Ole Miss","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"WISE JR., DEATRICH","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1471,"DATE":"2016-09-03","POS":"LB","OPP":"Louisiana Tech","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"ELLIS, BROOKS","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":863,"DATE":"2023-09-02","POS":"DL","OPP":"Western Caro.","CLASS":"JUNIOR","TEAM":"Arkansas","PLAYER":"HILL, JON","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":236,"DATE":"2017-10-21","POS":"LB","OPP":"Auburn","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"GREENLAW, DRE","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1457,"DATE":"2016-11-12","POS":"DB","OPP":"LSU","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"LIDDELL, JOSH","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1473,"DATE":"2016-10-01","POS":"LB","OPP":"Alcorn","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"ELLIS, BROOKS","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":508,"DATE":"2021-11-26","POS":"DB","OPP":"Missouri","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"BROWN, MONTARIC","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1446,"DATE":"2016-12-29","POS":"LB","OPP":"Virginia Tech","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"EUGENE JR., DWAYNE","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":115,"DATE":"2019-10-26","OPP":"Alabama","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"CURL, KAMREN","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1493,"DATE":"2016-12-29","POS":"DB","OPP":"Virginia Tech","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"COLLINS, JARED","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":230,"DATE":"2016-10-22","POS":"DL","OPP":"Auburn","CLASS":"JUNIOR","TEAM":"Arkansas","PLAYER":"BEANUM, TEVIN","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":851,"DATE":"2023-09-02","POS":"LB","OPP":"Western Caro.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"THOMAS, JAHEIM","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":114,"DATE":"2019-10-26","POS":"LB","OPP":"Alabama","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"MORGAN, GRANT","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":226,"DATE":"2016-10-22","POS":"LB","OPP":"Auburn","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"ELLIS, BROOKS","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":875,"DATE":"2023-10-07","POS":"DL","OPP":"Ole Miss","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"JACKSON, LANDON","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":225,"DATE":"2016-10-22","POS":"DB","OPP":"Auburn","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"LIDDELL, JOSH","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":56,"DATE":"2014-10-11","POS":"LB","OPP":"Alabama","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"MITCHELL, BRAYLON","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":885,"DATE":"2023-11-04","POS":"LB","OPP":"Florida","CLASS":"SOPHOMORE","TEAM":"Arkansas","PLAYER":"PAUL JR., CHRIS","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1415,"DATE":"2016-12-29","POS":"LB","OPP":"Virginia Tech","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"GREENLAW, DRE","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1476,"DATE":"2016-11-12","POS":"LB","OPP":"LSU","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"ELLIS, BROOKS","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1546,"DATE":"2017-11-24","POS":"LB","OPP":"Missouri","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"MORGAN, GRANT","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":223,"DATE":"2016-10-22","POS":"LB","OPP":"Auburn","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"EUGENE JR., DWAYNE","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":498,"DATE":"2021-09-18","POS":"LB","OPP":"Ga. Southern","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"MORGAN, GRANT","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":493,"DATE":"2021-10-23","POS":"LB","OPP":"Ark.-Pine Bluff","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"EDWARDS, DEON","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1382,"DATE":"2015-09-05","POS":"LB","OPP":"UTEP","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"WILLIAMS, JOSH","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1331,"DATE":"2015-10-03","POS":"DL","OPP":"Tennessee","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"LEDBETTER, JEREMIAH","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1368,"DATE":"2015-09-19","POS":"DB","OPP":"Texas Tech","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"GAINES, ROHAN","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1313,"DATE":"2015-11-14","POS":"LB","OPP":"LSU","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"ELLIS, BROOKS","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1312,"DATE":"2015-11-07","POS":"LB","OPP":"Ole Miss","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"ELLIS, BROOKS","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":211,"DATE":"2015-10-24","POS":"DL","OPP":"Auburn","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"LEDBETTER, JEREMIAH","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":847,"DATE":"2023-10-07","POS":"DB","OPP":"Ole Miss","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"WALCOTT, ALFAHIYM","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1310,"DATE":"2015-10-03","POS":"LB","OPP":"Tennessee","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"ELLIS, BROOKS","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1397,"DATE":"2016-10-01","POS":"LB","OPP":"Alcorn","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"HARRIS, DE'JON","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1268,"DATE":"2015-09-05","POS":"DB","OPP":"UTEP","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"RAMIREZ, SANTOS","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1290,"DATE":"2015-09-12","POS":"DB","OPP":"Toledo","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"LIDDELL, JOSH","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":795,"DATE":"2023-10-21","POS":"DB","OPP":"Mississippi St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"CLARK, HUDSON","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1293,"DATE":"2015-11-14","POS":"DB","OPP":"LSU","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"LIDDELL, JOSH","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":796,"DATE":"2023-11-04","POS":"DB","OPP":"Florida","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"CLARK, HUDSON","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1262,"DATE":"2015-11-21","POS":"DB","OPP":"Mississippi St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"RICHARDSON II, KEVIN","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1252,"DATE":"2015-10-31","POS":"LB","OPP":"UT Martin","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"GREENLAW, DRE","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":197,"DATE":"2014-08-30","POS":"LB","OPP":"Auburn","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"SPAIGHT, MARTRELL","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":466,"DATE":"2018-10-27","POS":"LB","OPP":"Vanderbilt","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"POOL, BUMPER","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":783,"DATE":"2022-12-28","POS":"DB","OPP":"Kansas","CLASS":"SOPHOMORE","TEAM":"Arkansas","PLAYER":"MCADOO, QUINCEY","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":848,"DATE":"2023-10-21","POS":"DB","OPP":"Mississippi St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"WALCOTT, ALFAHIYM","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1241,"DATE":"2014-10-25","POS":"DL","OPP":"UAB","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"LOEWEN, MITCHELL","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":785,"DATE":"2023-09-09","POS":"DL","OPP":"Kent St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"CARTER, TAUREAN","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":811,"DATE":"2023-10-07","POS":"LB","OPP":"Ole Miss","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"GRIER, ANTONIO","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1551,"DATE":"2017-11-18","OPP":"Mississippi St.","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"CURL, KAMREN","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":447,"DATE":"2016-09-10","POS":"DL","OPP":"TCU","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"LEDBETTER, JEREMIAH","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":744,"DATE":"2022-11-25","POS":"LB","OPP":"Missouri","CLASS":"JUNIOR","TEAM":"Arkansas","PLAYER":"SANDERS, DREW","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":449,"DATE":"2016-09-10","POS":"DL","OPP":"TCU","CLASS":"JUNIOR","TEAM":"Arkansas","PLAYER":"BEANUM, TEVIN","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":753,"DATE":"2022-11-12","POS":"DL","OPP":"LSU","CLASS":"JUNIOR","TEAM":"Arkansas","PLAYER":"BALL, CAMERON","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1211,"DATE":"2014-11-28","POS":"DL","OPP":"Missouri","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"FLOWERS, TREY","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1194,"DATE":"2014-11-22","POS":"LB","OPP":"Ole Miss","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"SPAIGHT, MARTRELL","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":716,"DATE":"2022-11-19","POS":"DB","OPP":"Ole Miss","CLASS":"JUNIOR","TEAM":"Arkansas","PLAYER":"SLUSHER, MYLES","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":179,"DATE":"2023-11-11","POS":"DB","OPP":"Auburn","CLASS":"SOPHOMORE","TEAM":"Arkansas","PLAYER":"METCALF, TJ","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":439,"DATE":"2016-09-10","POS":"LB","OPP":"TCU","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"GREENLAW, DRE","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":177,"DATE":"2023-11-11","POS":"LB","OPP":"Auburn","CLASS":"SOPHOMORE","TEAM":"Arkansas","PLAYER":"CROOK, JORDAN","RES":"0"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":735,"DATE":"2022-12-28","POS":"DB","OPP":"Kansas","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"MCGLOTHERN, DWIGHT","RES":"1"},"stats":{"DTACKA":"4"}},{"metadata":{"ID":1202,"DATE":"2014-11-15","POS":"DB","OPP":"LSU","CLASS":"SENIOR","TEAM":"Arkansas","PLAYER":"GAINES, ROHAN","RES":"1"},"stats":{"DTACKA":"4"}}]"""

In [127]:
results = json.loads(results)

In [129]:
m = [x["metadata"] for x in results]

In [131]:
results = pd.DataFrame(m)

In [135]:
results[results["PLAYER"] == "AGIM, MCTELVIN"]

,ID,DATE,POS,OPP,CLASS,TEAM,PLAYER,RES
13,1712,2018-10-20,DL,Tulsa,SENIOR,Arkansas,"AGIM, MCTELVIN",1
20,1568,2017-11-18,DL,Mississippi St.,SENIOR,Arkansas,"AGIM, MCTELVIN",0
27,1713,2018-11-10,DL,LSU,SENIOR,Arkansas,"AGIM, MCTELVIN",0

In [151]:
x = """
s_defensive_extra_points
s_field_goal_attempt_longest
s_field_goal_attempts_1to19
s_field_goal_attempts_20to29
s_field_goal_attempts_30to39
s_field_goal_attempts_40to49
s_field_goal_attempts_50to59
s_field_goal_attempts_60plus
s_field_goal_made_longest
s_field_goals_attempted
s_field_goals_blocked
s_field_goals_blocked_by
s_field_goals_made
s_field_goals_made_1to19
s_field_goals_made_20to29
s_field_goals_made_30to39
s_field_goals_made_40to49
s_field_goals_made_50to59
s_field_goals_made_60plus
s_fumble_return_longest
s_fumble_return_total
s_fumble_return_touchdowns
s_fumble_return_yards
s_fumbles_forced
s_fumbles_lost
s_fumbles_recovered
s_goal_efficiency_touchdowns
s_interceptions_return_longest
s_interceptions_return_yards
s_interceptions_touchdowns
s_kick_on_side_attempts
s_kick_returns_longest
s_kick_returns_total
s_kick_returns_touchdowns
s_kick_returns_yards
s_kickoffs_gross_yards
s_kickoffs_net_yards
s_kickoffs_out_of_bound
s_kickoffs_returned
s_kickoffs_total
s_kickoffs_touchbacks
s_kicks_blocked
s_kicks_blocked_by
s_kicks_on_side
s_minutes
s_pass_break_ups
s_pass_interceptions
s_pass_quarterback_hurries
s_passes
s_passes_completed
s_passes_intercepted
s_passes_left
s_passes_longest
s_passes_middle
s_passes_right
s_passes_sacked
s_passes_touchdowns
s_passes_yards
s_passes_yards_sacked
s_passing_0
s_passing_10
s_passing_20
s_passing_30
s_passing_40
s_passing_50
s_passing_negative
s_pat_attempts
s_pat_blocked_kicks
s_pat_blocked_kicks_by
s_pat_fumble_return_conversions
s_pat_fumble_returns
s_pat_interception_return_conversions
s_pat_kick_return_conversions
s_pat_kick_returns
s_pat_kicks_attempted
s_pat_kicks_made
s_pat_made
s_pat_pass_attempts
s_pat_passes
s_pat_receives
s_pat_rush_attempts
s_pat_rushes
s_pat_two_points_attempt
s_pat_two_points_made
s_penalty
s_penalty_yards
s_plays_all_purpose_total
s_plays_total
s_points
s_punt_returns
s_punt_returns_0
s_punt_returns_10
s_punt_returns_20
s_punt_returns_30
s_punt_returns_40
s_punt_returns_50
s_punt_returns_longest
s_punt_returns_touchdown
s_punt_returns_yards
s_punts
s_punts_50plus
s_punts_average
s_punts_blocked
s_punts_blocked_by
s_punts_fair_catches
s_punts_inside20
s_punts_longest
s_punts_touchbacks
s_punts_yards
s_punts_yards_net
s_receiving_0
s_receiving_10
s_receiving_20
s_receiving_30
s_receiving_40
s_receiving_50
s_receiving_negative
s_receptions
s_receptions_longest
s_receptions_touchdown
s_receptions_yards
s_receptions_yards_after_catch
s_red_zone_passing
s_rushing_0
s_rushing_10
s_rushing_20
s_rushing_30
s_rushing_40
s_rushing_50
s_rushing_attempts
s_rushing_left
s_rushing_longest
s_rushing_middle
s_rushing_net_yards_average
s_rushing_right
s_rushing_touchdowns
s_rushing_yards_gain
s_rushing_yards_loss
s_rushing_yards_net
s_sacks_assisted
s_sacks_total
s_sacks_unassisted
s_sacks_yards
s_safeties_two_points
s_tackles_assisted
s_tackles_for_loss_assisted
s_tackles_for_loss_solo
s_tackles_for_loss_total
s_tackles_solo
s_tackles_total
s_tackles_yards
s_takeaways
s_touchdowns
s_turnovers_caused
s_turnovers_committed
s_yards_all_purpose_total
s_yards_offensive_total
s_interceptions_average
s_kickoffs_gross_average
s_kickoffs_net_average
s_kick_returns_average
s_fumble_return_yards_average
s_passes_average_yards_per_completion
s_passes_yards_per_attempt
s_passes_yards_per_catch
s_punt_returns_average
s_punts_net_average
s_receptions_average
s_yards_per_play_average
s_field_goals_percentage
s_goal_efficiency_percentage
s_passes_interception_percentage
s_passes_percentage
s_passes_touchdown_percentage
s_pat_kicks_percentage
s_pat_percentage
s_pass_efficiency
s_fumbles_total
"""

In [153]:
len([y.strip() for y in x.strip().split("\n") if len(y) > 0])

178